// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/alwiirfan/internal/entities"
	mock "github.com/stretchr/testify/mock"

	request "github.com/alwiirfan/internal/dto/request"
)

// BookRepository is an autogenerated mock type for the BookRepository type
type BookRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, book
func (_m *BookRepository) Create(ctx context.Context, book *entities.Book) error {
	ret := _m.Called(ctx, book)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Book) error); ok {
		r0 = rf(ctx, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAll provides a mock function with given fields: ctx
func (_m *BookRepository) DeleteAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *BookRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, page, pageSize
func (_m *BookRepository) FindAll(ctx context.Context, page int, pageSize int) ([]*entities.Book, int64, error) {
	ret := _m.Called(ctx, page, pageSize)

	var r0 []*entities.Book
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*entities.Book, int64, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*entities.Book); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAllSearch provides a mock function with given fields: ctx, page, pageSize, req
func (_m *BookRepository) FindAllSearch(ctx context.Context, page int, pageSize int, req *request.SearchBookRequest) ([]*entities.Book, int64, error) {
	ret := _m.Called(ctx, page, pageSize, req)

	var r0 []*entities.Book
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *request.SearchBookRequest) ([]*entities.Book, int64, error)); ok {
		return rf(ctx, page, pageSize, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *request.SearchBookRequest) []*entities.Book); ok {
		r0 = rf(ctx, page, pageSize, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *request.SearchBookRequest) int64); ok {
		r1 = rf(ctx, page, pageSize, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, *request.SearchBookRequest) error); ok {
		r2 = rf(ctx, page, pageSize, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *BookRepository) FindByID(ctx context.Context, id string) (*entities.Book, error) {
	ret := _m.Called(ctx, id)

	var r0 *entities.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Book); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByISBN provides a mock function with given fields: ctx, isbn
func (_m *BookRepository) FindByISBN(ctx context.Context, isbn string) (*entities.Book, error) {
	ret := _m.Called(ctx, isbn)

	var r0 *entities.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Book, error)); ok {
		return rf(ctx, isbn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Book); ok {
		r0 = rf(ctx, isbn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isbn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, book
func (_m *BookRepository) Update(ctx context.Context, book *entities.Book) error {
	ret := _m.Called(ctx, book)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Book) error); ok {
		r0 = rf(ctx, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBookRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookRepository creates a new instance of BookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookRepository(t mockConstructorTestingTNewBookRepository) *BookRepository {
	mock := &BookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
